### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by nonimportant** [SlyFryFrog/Flashcards#1] opened 2022-01-24 16:04 UTC
Error when trying to run the app:
```
Traceback (most recent call last):
  File "C:\Users\-----\Downloads\Flashcards-main\Flashcards-main\Flash Cards Program.py", line 139, in <module>
    build_dict()
  File "C:\Users\-----\Downloads\Flashcards-main\Flashcards-main\Flash Cards Program.py", line 133, in build_dict
    key, val = line.split("; ")
ValueError: not enough values to unpack (expected 2, got 1)

[process exited with code 1]
```

I think the problem originates from the line `key, val = line.split("; ")`, where you're trying to get the verb and its definition by splitting each line by a semicolon. However, in [`verbs.txt`](https://github.com/SlyFryFrog/Flashcards/blob/main/verbs.txt), the values are separated by a comma, not a semicolon.

**Comment by SlyFryFrog** [comment] 2022-01-24 16:17
Thank you for reporting this issue, I changed the way the code split the text file and never updated the text file on here. The issue is now fixed.

**Closed by SlyFryFrog** 2022-01-24 16:17 UTC
